version: '3.8'

services:
  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ROOTNAME
      MINIO_ROOT_PASSWORD: CHANGEME123
    ports:
      - "9002:9000"
      - "9003:9001"
    volumes:
      - minio_data:/data
    networks:
      - mlflow_network
    restart: unless-stopped

  minio_mc:
    image: minio/mc
    depends_on:
      - minio
    environment:
      AWS_ACCESS_KEY_ID: ROOTNAME
      AWS_SECRET_ACCESS_KEY: CHANGEME123
      MLFLOW_USER: MLFlowUser
      MLFLOW_PASS: MyFlowPass
    volumes:
      - ./setup_minio.sh:/setup_minio.sh
    entrypoint: /bin/sh
    command: -c "chmod +x /setup_minio.sh && /setup_minio.sh"
    networks:
      - mlflow_network

  mysql_mlflow:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_USER: mlflow_user
      MYSQL_PASSWORD: mlflow_password
      MYSQL_DATABASE: mlflow_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mlflow_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  adminer:
    image: adminer
    depends_on:
      - mysql_mlflow
    environment:
      ADMINER_DEFAULT_SERVER: mysql_mlflow
    ports:
      - "8080:8080"
    networks:
      - mlflow_network
    restart: unless-stopped

  mlflow:
    build:
      context: ./mlflow_server
      dockerfile: Dockerfile
    image: mlflow-custom
    environment:
      AWS_ACCESS_KEY_ID: MLFlowUser
      AWS_SECRET_ACCESS_KEY: MyFlowPass
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
    command: >
      sh -c "sleep 10 &&
      mlflow server --backend-store-uri 'mysql+pymysql://mlflow_user:mlflow_password@mysql_mlflow/mlflow_db'
      --default-artifact-root 's3://flow-bucket/'
      --host 0.0.0.0 --port 5000"
    depends_on:
      mysql_mlflow:
        condition: service_healthy
      minio:
        condition: service_started
    ports:
      - "5000:5000"
    volumes:
      - mlflow_data:/mlflow
    networks:
      - mlflow_network
    restart: unless-stopped

volumes:
  minio_data:
    driver: local
  mysql_data:
    driver: local
  mlflow_data:
    driver: local

networks:
  mlflow_network:
    driver: bridge